INPUT_FILE="../One_Shifting_Results/Spatial_ATAC/activity_counts.feather"
GROUND_TRUTH_FILE="../One_Shifting_Results/Spatial_RNA/rna_counts.feather"
READ_DIR="../One_Shifting_Results/Spatial_INPUT_ATAC"
V1="Spatial_ATAC"
V2="Spatial_RNA"
V2_norm_factor="no_norm"
V2_trans_factor="no_trans"